name: flutter_application_1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8
  animated_toggle_switch: ^0.8.2
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  provider: ^6.1.2
  google_sign_in: ^6.2.1

  flutter_localizations:
    sdk: flutter
  dio: ^5.9.0
  # ----------------------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  generate: true
  # ----------------------------------------------------

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/splash_logo/
    - assets/onbording/
    - assets/avatar/
    - assets/icon/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
